#!/bin/sh
# If Xresources is present, load it
[ -f ~/.Xresources ] && xrdb ~merge ~/.Xresources

# Turn off beeps
xset -b

# Turn on numlock
numlockx &

# Make sure D-Bus is running
# See http://www.nurdletech.com/linux-notes/agents/keyring.html for more detail
if [ -z "${DBUS_SESSION_BUS_ADDRESS}" ]
then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# Get gnome-keyring's variables exported
export "$(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)"

# Configure nvidia modesetting
#xrandr --setprovideroutputsource modesetting NVIDIA-0
#xrandr --setprovideroutputsource nouveau
#xrandr --auto

set enable-bracketed-paste off

# Start X without consolekit
exec i3
