theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "enp5s0"
format = "{ip} {bitrate}"
hide_inactive = true
hide_missing = true
interval = 15

[[block]]
block = "net"
device = "enp7s0f3u1u1u1"
format = "{ip} {bitrate}"
hide_inactive = true
hide_missing = true
interval = 15

[[block]]
block = "net"
device = "wlp3s0"
format = "{ssid} {signal_strength} {ip}"
hide_inactive = true
hide_missing = true
interval = 15

[[block]]
block = "net"
device = "tun0"
format = "{ip}"
hide_inactive = true
hide_missing = true
interval = 15

[[block]]
block = "sound"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
warning = 20.0
alert = 10.0
interval = 300

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"
interval = 30

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
format = "{min}/{max}/{average} min/max/avg"
chip = "k10temp-pci-*"
interval = 10

[[block]]
block = "battery"
interval = 60
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 5
format = "%m-%d %T"

[[block]]
block = "time"
interval = 5
format = "%m-%d %T %Z"
timezone = "UTC"
