theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "enp0s31f6"
ip = true
speed_up = false
speed_down = false
hide_inactive = true
hide_missing = true
interval = 15

[[block]]
block = "net"
device = "enp47s0u2u1u2c2"
ip = true
speed_up = false
speed_down = false
hide_inactive = true
hide_missing = true
interval = 15

[[block]]
block = "net"
device = "wlp82s0"
ip = true
ssid = true
bitrate = true
speed_up = false
speed_down = false
hide_inactive = true
hide_missing = true
interval = 15

[[block]]
block = "net"
device = "tun0"
ip = true
hide_inactive = true
hide_missing = true
interval = 15

[[block]]
block = "sound"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0
interval = 300

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
interval = 30

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
format = "{min}° min, {max}° max, {average}° avg"
chip = "coretemp-isa-*"
interval = 10

[[block]]
block = "battery"
interval = 60
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 5
format = "%m-%d %T"

[[block]]
block = "time"
interval = 5
format = "%m-%d %T"
timezone = "UTC"
