[theme]
theme = "solarized-dark"

[icons]
icons = "awesome4"

[[block]]
block = "external_ip"
format = "$ip $asn"
interval = 300

[[block]]
block = "net"
device = "enp5s0"
format = "$icon $ip $speed_down.eng(prefix:M)"
interval = 15

[[block]]
block = "net"
device = "enp7s0f3u1u1u1"
format = "$icon $ip $speed_down.eng(prefix:M)"
interval = 15

[[block]]
block = "net"
format = "$icon"
interval = 15

[[block]]
block = "net"
device = "tun0"
format = "$icon $ip"
interval = 15

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "$icon $available"
format_alt = "$icon $available/$total"
alert_unit = "GB"
warning = 20.0
alert = 10.0
interval = 300

[[block]]
block = "memory"
format = "$icon $mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M) ($mem_total_used_percents.eng(w:2))"
format_alt = "$icon_swap $swap_free.eng(prefix:M)/$swap_total.eng(prefix:M) ($swap_used_percents.eng(w:2))"
interval = 5

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5
format = "$icon $1m.eng(w:4)"

[[block]]
block = "temperature"
format = "$icon $average avg, $max max"
chip = "k10temp-pci-*"
interval = 10

[[block]]
block = "time"
interval = 5
[block.format]
full  = "$icon $timestamp.datetime(f:'%m-%d %T %Z')"
short = "$icon $timestamp.datetime(f:%R)"

[[block]]
block = "time"
interval = 5
timezone = "UTC"
[block.format]
full  = "$icon $timestamp.datetime(f:'%m-%d %T %Z')"
short = "$icon $timestamp.datetime(f:%R)"

[[block]]
block = "battery"
interval = 60
format = "$icon $percentage"

[[block]]
block = "sound"

